# Generated by Django 4.2.16 on 2024-10-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='complaint',
            name='evidences',
            field=models.TextField(blank=True),
        ),
    ]
